name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v1
    - name: 'Install Node'
      uses: actions/setup-node@v1
      with:
        version: '10.x'
    - name: 'npm install and build'
      run: |
        npm install
        npm run build
    - name: 'Deploy to firebase'
      uses: w9jds/firebase-action@7d6b2b058813e1224cdd4db255b2f163ae4084d3
      with:
        args: 'deploy'
        firebase_token: ${{ secrets.FIREBASE_TOKEN }}
