name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v1
    - name: 'Install Node'
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: 'npm install and build'
      run: |
        npm install
        npm run build
    - name: 'Deploy to firebase'
      uses: maxburkhardt/firebase-action@e450b330136fc27897ecf6f2b5c7ba4bf5d9a251
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: 'deploy'
